x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  env_file:
    - .env
  networks:
    - bms
  logging:
    driver: "json-file"
    options:
      max-size: "20m"
      max-file: "3"

services:
  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: bms-cc01
    command: >
      watchmedo auto-restart --directory=./ --pattern='*.py' --recursive
      --
      celery -A bms worker
      --loglevel=info
      --concurrency=2
      --max-tasks-per-child=50
    depends_on:
      - django
      - redis
    volumes:
      - .:/code/
      - project_name_media_volume:/code/media
    <<: *common

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: bms-cb01
    command: >
      watchmedo auto-restart --directory=./ --pattern='*.py' --recursive
      --
      celery -A bms beat
      -l info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
      - django
      - redis
    volumes:
      - .:/code/
      - project_name_media_volume:/code/media
    <<: *common

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: bms-dc01
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - project_name_static_volume:/code/static
      - project_name_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    image: mher/flower:0.9.7
    container_name: bms-fc01
    command: >
      flower
      --broker=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB:-0}
      --broker_api=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB:-0}
      --port=${FLOWER_PORT:-5555}
      --basic_auth=${FLOWER_USERNAME:-admin}:${FLOWER_PASSWORD:-admin}
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    environment:
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB:-0}
    depends_on:
      - celery
    <<: *common

  postgres:
    image: postgres:18-alpine
    container_name: bms-pc01
    environment:
      - PGDATA=/var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    volumes:
      - project_name_postgres_data:/var/lib/postgresql
    # for default settings / maximum efficiency, comment from here to ...
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 256M
    # ... all the way here
    <<: *common

  redis:
    image: redis:8.4.0-alpine
    container_name: bms-rc01
    volumes:
      - project_name_redis_data:/data
    # for default settings / maximum efficiency, comment from here to ...
    command: >
      redis-server
      --maxmemory 80mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 80M
    # ... all the way here
    <<: *common

networks:
  bms:
    driver: bridge

volumes:
  project_name_postgres_data:
  project_name_redis_data:
  project_name_static_volume:
  project_name_media_volume:
