"""Phase 2 - plain Django views, user-scoped.

Two versions of the SAME endpoint are here so you can compare:

  AccountListView   - class-based, protected by LoginRequiredMixin
  account_list_fbv  - function-based, protected by @login_required

Only the class-based one is routed. The function is there to read.
"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from .models import BankAccount


def _serialize(account):
    """Turn one BankAccount into a JSON-safe dict.

    Written by hand because JsonResponse cannot encode a model instance or a
    Decimal. Phase 3 deletes this function entirely.
    """
    return {
        "id": account.id,
        "account_number": account.account_number,
        # Reaching THROUGH two foreign keys: account -> bank_branch -> bank.
        # Each dot is normally a separate query. select_related() below turns
        # all of it into one JOIN.
        "bank_name": account.bank_branch.bank.name,
        "branch_name": account.bank_branch.name,
        "account_type": account.account_type,
        # get_FOO_display() is generated by Django for any field with choices.
        # "savings" -> "Savings"
        "account_type_label": account.get_account_type_display(),
        # Decimal is NOT JSON serializable - JsonResponse raises TypeError.
        # str() keeps it exact. float() would lose precision, which is
        # unacceptable for money.
        "balance": str(account.balance),
        "is_active": account.is_active,
    }


class AccountListView(LoginRequiredMixin, View):
    """GET /accounts/ -> the CURRENT user's accounts only.

    LoginRequiredMixin MUST come before View in the base list. Python walks
    the bases left to right, so putting it after View means View.dispatch()
    wins and the login check never runs.

    Anonymous request -> 302 to settings.LOGIN_URL with ?next=/accounts/
    """

    def get(self, request):
        # THE SECURITY BOUNDARY of this whole app.
        #
        # filter(user=request.user) is what stops customer A reading customer
        # B's balance. In Phase 4 this exact line moves into get_queryset();
        # in Phase 5 staff get an override. Get it wrong and the API leaks.
        accounts = (
            BankAccount.objects.filter(user=request.user)
            # Without this: 1 query for the list, then 2 MORE per account
            # (one for bank_branch, one for bank). That is the N+1 problem.
            # With it: a single query containing two INNER JOINs.
            .select_related("bank_branch", "bank_branch__bank")
            .order_by("-created")
        )

        return JsonResponse(
            {
                "user": request.user.username,
                "count": accounts.count(),
                "accounts": [_serialize(a) for a in accounts],
            }
        )


# ---------------------------------------------------------------------------
# The same thing as a function view, for comparison. Not routed.
# ---------------------------------------------------------------------------
@login_required
def account_list_fbv(request):
    """Identical behaviour, different protection mechanism.

    @login_required REPLACES this function with a wrapper that checks
    request.user.is_authenticated first. Roughly:

        def wrapper(request, *a, **kw):
            if request.user.is_authenticated:
                return account_list_fbv(request, *a, **kw)
            return redirect_to_login(request.get_full_path(), settings.LOGIN_URL)

    Django's URL resolver calls that wrapper, never this body directly.
    LoginRequiredMixin above does the same job by overriding dispatch().
    """
    accounts = (
        BankAccount.objects.filter(user=request.user)
        .select_related("bank_branch__bank")
        .order_by("-created")
    )
    return JsonResponse({"accounts": [_serialize(a) for a in accounts]})
